version: '3.8'

services:
  fastapi:
    build: .
    container_name: fastapi
    volumes:
      - ./backend-api:/home/app/
    ports:
      - 23005:8000
    environment:
      SECRET_KEY: 9cef962019e98c0f4ed951b979d615cbaa98e51edd464ca5cc5c99349f5b9e6b
      PYTHONPATH: /home/app
    networks:
      - fastapi-network
    restart: always
  
  mongo:
    build: ./mongo/
    restart: always
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: fastapidb 
    ports:
      - 23006:27017
    networks:
      - fastapi-network
    command: mongod --replSet rs0 --keyFile /data/configdb/keyfile
    volumes:
      - ./mongo/mongodb_data:/data/db
      - ./mongo/data_import:/home/data_import
    healthcheck:
      test: |
        echo "try { 
          rs.status(); 
          var cfg = rs.conf(); 
          cfg.members[0].host = 'mongo:27017'; 
          rs.reconfig(cfg, {force: true}); 
        } catch (err) { 
          rs.initiate({_id:'rs0',members:[{_id:0,host:'mongo:27017'}]}) 
        }" | mongosh -u root -p example --port 27017 --quiet
      interval: 5s
      timeout: 30s
      start_period: 0s
      retries: 30

networks:
  fastapi-network:
    driver: bridge
